# Generated by Django 3.2.4 on 2021-06-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Product Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Product Price')),
                ('inventory', models.PositiveIntegerField(verbose_name='Product Inventory')),
                ('product_category', models.ManyToManyField(null=True, to='products.Category')),
            ],
        ),
    ]
